CREATE SEQUENCE BO_NO_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO BO (BO_NO,BO_TITLE,EMP_NO,
				BO_REGDATE,BO_LIKE_COUNT,BO_VIEW_COUNT
				,BO_CONTENT ,BO_STATUS,BO_DEL_YN,
				REG_ID,REG_DATE,MOD_ID
				,MOD_DATE)
VALUES('BO' || TO_CHAR(BO_NO_SEQ.NEXTVAL,'FM0000'),'제목2','관리자',
		SYSDATE,0,0
		,'내용2','announcements','N'
		,'관리자',SYSDATE,'관리자'
		,SYSDATE);

	SELECT BO_NO,EMP_NO,BO_STATUS,BO_TITLE,BO_CONTENT ,BO_REGDATE,BO_LIKE_COUNT,BO_VIEW_COUNT,BO_DEL_YN ,MOD_ID ,MOD_DATE 
			FROM BO
			WHERE BO_STATUS ='announcements' AND BO_DEL_YN ='N'
			ORDER BY BO_REGDATE DESC;
	
	
SELECT *
	FROM BO
	ORDER BY BO_REGDATE DESC;
	
SELECT *
	FROM BO
	WHERE BO_DEL_YN ='Y';

SELECT BO_NO,EMP_NO,BO_STATUS,BO_TITLE,BO_CONTENT ,BO_REGDATE,BO_LIKE_COUNT,BO_VIEW_COUNT,BO_DEL_YN ,MOD_ID ,MOD_DATE 
			FROM BO
			WHERE BO_NO='A0021';
		
UPDATE BO 
SET BO_TITLE ='수정1', BO_CONTENT ='내용수정1' 
WHERE BO_NO = 'A0021';

UPDATE BO SET BO_VIEW_COUNT = BO_VIEW_COUNT +1
WHERE BO_NO ='A0102';

UPDATE BO SET BO_DEL_YN ='Y'
WHERE BO_NO = 'A0102';

SELECT *
	FROM BO;

DELETE FROM BO WHERE BO_NO ='A0092';