CREATE SEQUENCE BO_NO_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO BO (BO_NO,BO_TITLE,EMP_NO,
				BO_REGDATE,BO_LIKE_COUNT,BO_VIEW_COUNT
				,BO_CONTENT ,BO_STATUS,BO_DEL_YN,
				REG_ID,REG_DATE,MOD_ID
				,MOD_DATE)
VALUES('A' || TO_CHAR(BO_NO_SEQ.NEXTVAL,'FM0000'),#{bo_title},#{emp_no},
		SYSDATE,0,0
		,#{bo_content},#{bo_status},'N'
		,#{reg_id},SYSDATE,#{mod_id}
		,SYSDATE);