INSERT INTO GEO.EMP
(EMP_NO, EMP_POS, EMP_DEPT, EMP_PW, EMP_NAME, EMP_GENDER, EMP_HIREDATE, EMP_EMAIL, EMP_PHONE, EMP_BIRTH, EMP_ADDRESS, EMP_AUTH, EMP_STATUS, EMP_RETIREDATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
VALUES('PR001', 'PO006', 'DE001', 'jsy3029', '정수용', 'M', TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 'bcjsy@naver.com', '010-2597-3029', '1994-04-24', '부천시', 'A', 'Y', '', '수용', TO_CHAR(SYSDATE, 'YYYY-MM-DD'), '수용', TO_CHAR(SYSDATE, 'YYYY-MM-DD'));


SELECT EMP_NO , (SELECT CODE_NAME FROM COM WHERE DIVISION = '직급') , (SELECT CODE_NAME FROM COM WHERE DIVISION = '부서') , EMP_NAME , EMP_GENDER , EMP_HIREDATE , EMP_EMAIL , EMP_PHONE , EMP_BIRTH , EMP_ADDRESS
	FROM EMP e ;
	
SELECT CODE_NAME 
	FROM COM
	WHERE DIVISION = '직급';

SELECT CODE_NAME 
	FROM COM
	WHERE DIVISION = '부서';
	
INSERT INTO GEO.COM
(COMMON_CODE, CODE_NAME, DIVISION, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
VALUES('PO006', '부장', '직급', '수용', SYSDATE, '수용', SYSDATE);

INSERT INTO GEO.COM
(COMMON_CODE, CODE_NAME, DIVISION, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
VALUES('DE001', '개발', '부서', '수용', SYSDATE, '수용', SYSDATE);

UPDATE GEO.EMP
SET EMP_POS='PO005', EMP_DEPT='DE002', EMP_PW='수용1234', EMP_NAME='수용', EMP_GENDER='M'
WHERE EMP_NO='PR001';



SELECT TO_CHAR(VA_YEAR, 'YYYY')
	FROM VA_CHECK vc ;

SELECT EMP_HIREDATE 
	FROM EMP e 
	WHERE EMP_NO = 'PR001';

SELECT *
	FROM VA_CHECK vc ;

TO_CHAR((SYSDATE - (SELECT EMP_HIREDATE FROM EMP e)), 'YYYY')

INSERT INTO GEO.VA_CHECK
(EMP_NO, VA_YEAR, VA_CHECK_NUM, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
VALUES('PR001', SYSDATE, CASE (TO_CHAR((SYSDATE - (SELECT EMP_HIREDATE FROM EMP e WHERE EMP_NO = 'PR001')), 'YYYY'))
						WHEN '0000'
						THEN 15
						ELSE 16
						END
, '수용', SYSDATE, '수용', SYSDATE);

INSERT INTO GEO.VA_CHECK
(EMP_NO, VA_YEAR, VA_CHECK_NUM, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
SELECT 
    'PR001',
    TRUNC(SYSDATE),
    CASE 
        WHEN TRUNC(SYSDATE) - TRUNC((SELECT EMP_HIREDATE FROM EMP e WHERE e.EMP_NO = 'PR001')) = 0 THEN 15
        ELSE 16
    END,
    '수용',
    SYSDATE,
    '수용',
    SYSDATE
FROM DUAL;


UPDATE GEO.EMP
SET EMP_POS='PO004', EMP_DEPT='DE002', EMP_EMAIL='1234@gmail.com', EMP_PHONE='010-1234-5678', EMP_ADDRESS='asd'
WHERE EMP_NO='PR001';


SELECT EMP_NAME , EMP_DEPT , EMP_POS , 
EMP_GENDER , EMP_BIRTH , EMP_PHONE , 
EMP_EMAIL , EMP_ADDRESS , EMP_HIREDATE 
	FROM EMP e 
	WHERE EMP_NO = 'PR001';


UPDATE GEO.EMP
SET EMP_PW='1234'
WHERE EMP_NO='SY111';
