SELECT *
	FROM EMP e ;


INSERT INTO GEO.EMP
(EMP_NO, EMP_POS, EMP_DEPT, EMP_PW, EMP_NAME, EMP_GENDER, EMP_HIREDATE, EMP_EMAIL, EMP_PHONE, EMP_BIRTH, EMP_ADDRESS, EMP_AUTH, EMP_STATUS, EMP_RETIREDATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
VALUES('PR001', 'DE002', 'PO006', '1234', '정수용', '남', SYSDATE, 'chasersy@gmail.com', '010-0000-0000', SYSDATE, '경기도 부천시', 'A', 'Y', '', '관리자', SYSDATE, '관리자', SYSDATE);
