-- 쪽지 테이블 생성
CREATE TABLE "MSG" (
	"MSG_NO"	NUMBER		NOT NULL,
	"MSG_SEND_ID"	VARCHAR2(100)		NOT NULL,
	"MSG_RECV_ID"	VARCHAR2(100)		NOT NULL,
	"MSG_CONTENT"	CLOB		NOT NULL,
	"MSG_SEND_DATE"	DATE		NOT NULL,
	"MSG_RECV_READ_YN"	VARCHAR2(100)	DEFAULT 'N'	NOT NULL,
	"MSG_SEND_DEL_YN"	VARCHAR2(100)	DEFAULT 'N'	NOT NULL,
	"MSG_RECV_DEL_YN"	VARCHAR2(100)	DEFAULT 'N'	NOT NULL,
	"REG_ID"	VARCHAR2(100)		NOT NULL,
	"REG_DATE"	DATE		NOT NULL,
	"MOD_ID"	VARCHAR2(100)		NOT NULL,
	"MOD_DATE"	DATE		NOT NULL
);

-- 쪽지 테이블 PK 지정
ALTER TABLE "MSG" ADD CONSTRAINT "PK_MSG" PRIMARY KEY (
	"MSG_NO"
);

---------------------------------------------------------------------------------

-- *** 쪽지 테이블 삭제
DROP TABLE MSG;

---------------------------------------------------------------------------------

-- 받은 쪽지 리스트 조회
SELECT MSG_NO , MSG_SEND_ID , MSG_RECV_ID ,
		MSG_CONTENT , MSG_SEND_DATE , MSG_RECV_READ_YN ,
		MSG_SEND_DEL_YN , MSG_RECV_DEL_YN , REG_ID ,
		REG_DATE , MOD_ID , MOD_DATE 
	FROM MSG
	WHERE MSG_RECV_ID = 'HYUN'
	ORDER BY MSG_SEND_DATE DESC;

-- 보낸 쪽지 리스트 조회
SELECT MSG_NO , MSG_SEND_ID , MSG_RECV_ID ,
		MSG_CONTENT , MSG_SEND_DATE , MSG_RECV_READ_YN ,
		MSG_SEND_DEL_YN , MSG_RECV_DEL_YN , REG_ID ,
		REG_DATE , MOD_ID , MOD_DATE 
	FROM MSG
	WHERE MSG_SEND_ID = 'HYUN'
	ORDER BY MSG_SEND_DATE DESC;

-- 쪽지 상세 조회
SELECT MSG_NO , MSG_SEND_ID , MSG_RECV_ID ,
		MSG_CONTENT , MSG_SEND_DATE , MSG_RECV_READ_YN ,
		MSG_SEND_DEL_YN , MSG_RECV_DEL_YN , REG_ID ,
		REG_DATE , MOD_ID , MOD_DATE 
	FROM MSG
	WHERE MSG_NO = '9';

-- 쪽지 보내기 (insert)
INSERT INTO GEO.MSG
				(MSG_NO, MSG_SEND_ID, MSG_RECV_ID,
				MSG_CONTENT, MSG_SEND_DATE, REG_ID,
				REG_DATE, MOD_ID, MOD_DATE)
	VALUES(MSG_SEQ.NEXTVAL, 'KANG', 'HYUN',
	'더미데이터 추가', SYSDATE, 'ADMIN',
	SYSDATE, 'ADMIN', SYSDATE);
	
-- 쪽지 읽기 (update)
UPDATE GEO.MSG
	SET MSG_RECV_READ_YN='Y', MOD_DATE=SYSDATE
	WHERE MSG_NO='9';

-- 받은 쪽지 삭제 (update)
UPDATE GEO.MSG
	SET MSG_RECV_DEL_YN='Y', MOD_DATE=SYSDATE
	WHERE MSG_NO IN ('9','40');

-- 보낸 쪽지 삭제 (update)
UPDATE GEO.MSG
	SET MSG_SEND_DEL_YN='Y'	, MOD_DATE=SYSDATE
	WHERE MSG_NO IN ('9','40');

-- 쪽지 테이블 더미데이터 입력
INSERT INTO GEO.MSG
				(MSG_NO, MSG_SEND_ID, MSG_RECV_ID,
				MSG_CONTENT, MSG_SEND_DATE, MSG_RECV_READ_YN,
				MSG_SEND_DEL_YN, MSG_RECV_DEL_YN, REG_ID,
				REG_DATE, MOD_ID, MOD_DATE)
	VALUES(MSG_SEQ.NEXTVAL, 'HYUN', 'HYUN',
	'쪽지내용11', SYSDATE, 'N',
	'N', 'N', 'HYUN',
	SYSDATE, 'HYUN', SYSDATE);

-- 시퀀스 생성
CREATE SEQUENCE MSG_SEQ START WITH 1 INCREMENT BY 1;

-- 시퀀스 확인(1 추가됨 주의)
SELECT MSG_SEQ.NEXTVAL
	FROM DUAL;
	
-- 시퀀스 삭제
DROP SEQUENCE MSG_SEQ;

---------------------------------------------------------------------------------

-- 파일 시퀀스 생성
CREATE SEQUENCE FILE_SEQ START WITH 1 INCREMENT BY 1;

-- 파일 시퀀스 확인(1 추가됨 주의)
SELECT FILE_SEQ.NEXTVAL
	FROM DUAL;
	
-- 파일 시퀀스 삭제
DROP SEQUENCE FILE_SEQ;

-- 파일 업로드
INSERT INTO GEO."FILE"
		(FILE_NO, ORIGIN_NO, FILE_ONAME,
		FILE_SNAME, FILE_SIZE, FILE_TYPE,
		FILE_RANK, REG_ID, REG_DATE,
		MOD_ID, MOD_DATE)
	VALUES(MSG_SEQ.NEXTVAL, 141, '나몰빼미.png',
			'7937b1ad-2e33-4367-935e-9614881144de.png', '62.3', '3',
			0, 'HYUN', SYSDATE,
			'HYUN', SYSDATE);

-- 파일 다운로드
SELECT FILE_NO, ORIGIN_NO, FILE_ONAME,
		FILE_SNAME, FILE_SIZE, FILE_TYPE,
		FILE_RANK, FILE_DEL_YN, REG_ID,
		REG_DATE, MOD_ID, MOD_DATE
	FROM GEO."FILE"
	WHERE ORIGIN_NO = '156';

---------------------------------------------------------------------------------

SELECT *
	FROM EMP;
	
SELECT EMP_NO, EMP_POS, EMP_DEPT,
		EMP_PW, EMP_NAME, EMP_GENDER,
		EMP_HIREDATE, EMP_EMAIL, EMP_PHONE,
		EMP_BIRTH, EMP_ADDRESS, EMP_AUTH,
		EMP_STATUS, EMP_RETIREDATE, REG_ID,
		REG_DATE, MOD_ID, MOD_DATE
	FROM GEO.EMP
	WHERE EMP_NO = 'emp5' AND EMP_PW = '111';

---------------------------------------------------------------------------------	

-- 다수에게 쪽지 보내기 (다중 insert) 일단 안됨
--INSERT ALL
--	INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID,
--				MSG_CONTENT, MSG_SEND_DATE, REG_ID,
--				REG_DATE, MOD_ID, MOD_DATE)
--	VALUES (MSG_SEQ.NEXTVAL, 'ADMIN', 'USER01',
--				'쪽지내용11', SYSDATE, 'ADMIN',
--				SYSDATE, 'ADMIN', SYSDATE)
--	INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID,
--				MSG_CONTENT, MSG_SEND_DATE, REG_ID,
--				REG_DATE, MOD_ID, MOD_DATE)
--	VALUES (MSG_SEQ.NEXTVAL, 'ADMIN', 'USER02',
--				'쪽지내용11', SYSDATE, 'ADMIN',
--				SYSDATE, 'ADMIN', SYSDATE)
--	INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID,
--				MSG_CONTENT, MSG_SEND_DATE, REG_ID,
--				REG_DATE, MOD_ID, MOD_DATE)
--	VALUES (MSG_SEQ.NEXTVAL, 'ADMIN', 'USER03',
--				'쪽지내용11', SYSDATE, 'ADMIN',
--				SYSDATE, 'ADMIN', SYSDATE)
--	INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID,
--				MSG_CONTENT, MSG_SEND_DATE, REG_ID,
--				REG_DATE, MOD_ID, MOD_DATE)
--	VALUES (MSG_SEQ.NEXTVAL, 'ADMIN', 'USER04',
--				'쪽지내용11', SYSDATE, 'ADMIN',
--				SYSDATE, 'ADMIN', SYSDATE)
--	INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID,
--				MSG_CONTENT, MSG_SEND_DATE, REG_ID,
--				REG_DATE, MOD_ID, MOD_DATE)
--	VALUES (MSG_SEQ.NEXTVAL, 'ADMIN', 'USER05',
--				'쪽지내용11', SYSDATE, 'ADMIN',
--				SYSDATE, 'ADMIN', SYSDATE)
--SELECT 1 FROM DUAL;

-- GPT
--INSERT ALL
--    INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID, MSG_CONTENT, MSG_SEND_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
--    VALUES (MSG_SEQ.NEXTVAL, 'ADMIN', 'USER01', '쪽지내용11', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE)
--    INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID, MSG_CONTENT, MSG_SEND_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
--    VALUES (MSG_SEQ.NEXTVAL, 'ADMIN', 'USER02', '쪽지내용12', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE)
--    INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID, MSG_CONTENT, MSG_SEND_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
--    VALUES (MSG_SEQ.NEXTVAL, 'ADMIN', 'USER03', '쪽지내용13', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE)
--    INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID, MSG_CONTENT, MSG_SEND_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
--    VALUES (MSG_SEQ.NEXTVAL, 'ADMIN', 'USER04', '쪽지내용14', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE)
--    INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID, MSG_CONTENT, MSG_SEND_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
--    VALUES (MSG_SEQ.NEXTVAL, 'ADMIN', 'USER05', '쪽지내용15', SYSDATE, 'ADMIN', SYSDATE, 'ADMIN', SYSDATE)
--SELECT 1 FROM DUAL;


-- 안됨
--INSERT INTO MSG (MSG_NO, MSG_SEND_ID, MSG_RECV_ID,
--				MSG_CONTENT, MSG_SEND_DATE, REG_ID,
--				REG_DATE, MOD_ID, MOD_DATE) 
--		SELECT MAX(MSG_SEQ.NEXTVAL)+1, 'ADMIN', 'USER01',
--				'쪽지내용11', SYSDATE, 'ADMIN',
--				SYSDATE, 'ADMIN', SYSDATE
--			FROM DUAL
--	UNION ALL
--		SELECT MAX(MSG_SEQ.NEXTVAL)+1, 'ADMIN', 'USER02',
--				'쪽지내용11', SYSDATE, 'ADMIN',
--				SYSDATE, 'ADMIN', SYSDATE
--			FROM DUAL
--	UNION ALL
--		SELECT MAX(MSG_SEQ.NEXTVAL)+1, 'ADMIN', 'USER03',
--				'쪽지내용11', SYSDATE, 'ADMIN',
--				SYSDATE, 'ADMIN', SYSDATE
--			FROM DUAL
--	UNION ALL
--		SELECT MAX(MSG_SEQ.NEXTVAL)+1, 'ADMIN', 'USER04',
--				'쪽지내용11', SYSDATE, 'ADMIN',
--				SYSDATE, 'ADMIN', SYSDATE
--			FROM DUAL
--	UNION ALL
--		SELECT MAX(MSG_SEQ.NEXTVAL)+1, 'ADMIN', 'USER05',
--				'쪽지내용11', SYSDATE, 'ADMIN',
--				SYSDATE, 'ADMIN', SYSDATE
--			FROM DUAL;