SELECT *
	FROM EMP e ;
	

UPDATE GEO.EMP
SET EMP_STATUS='N', 
EMP_RETIREDATE = SYSDATE
WHERE EMP_NO='SY345';



UPDATE GEO.ATT
SET ATT_ARRIVE_TIME = SYSDATE,
    REG_ID = 'BB002',
    REG_DATE = SYSDATE
WHERE EMP_NO = 'BB002'
AND ATT_ARRIVE_TIME IS NULL
AND TO_CHAR(SYSDATE, 'YYYY-MM-DD') = TO_CHAR(REG_DATE, 'YYYY-MM-DD');


UPDATE GEO.ATT
SET ATT_LEFT_TIME = SYSDATE,
	MOD_ID = 'BB002',
	MOD_DATE = SYSDATE
WHERE EMP_NO = 'BB002'
AND ATT_LEFT_TIME IS NULL
AND TO_CHAR(SYSDATE, 'YYYY-MM-DD') = TO_CHAR(REG_DATE, 'YYYY-MM-DD')
AND ATT_ARRIVE_TIME IS NOT NULL;

UPDATE GEO.ATT
SET ATT_LEFT_TIME = SYSDATE,
	MOD_ID = 'ZZ001',
	MOD_DATE = SYSDATE
WHERE EMP_NO = 'ZZ001'
AND TO_CHAR(ATT_ARRIVE_TIME, 'yyyy-MM-dd') = TO_CHAR(SYSDATE, 'yyyy-MM-dd')
AND ATT_ARRIVE_TIME IS NOT NULL;

-- 연차 생성 --

INSERT INTO GEO.VA_CHECK
(EMP_NO, VA_YEAR, VA_CHECK_NUM, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
SELECT e.EMP_NO, , '', '', ''),
	'batch', TO_CHAR(SYSDATE, 'yyyy-MM-dd')
	FROM EMP e
	WHERE e.EMP_STATUS = 'ST001';


INSERT INTO GEO.VA_CHECK
(EMP_NO, VA_YEAR, VA_CHECK_NUM, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
SELECT 
    'PR001',
    TRUNC(SYSDATE),
    CASE 
        WHEN TRUNC(SYSDATE) - TRUNC((SELECT EMP_HIREDATE FROM EMP e WHERE e.EMP_NO = 'PR001')) = 0 THEN 15
        ELSE 16
    END,
    '수용',
    SYSDATE,
    '수용',
    SYSDATE
FROM DUAL;


INSERT INTO GEO.VA_CHECK
(EMP_NO, VA_YEAR, VA_CHECK_NUM, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
SELECT 
    e.EMP_NO,
    TRUNC(SYSDATE, 'YYYY'),
    CASE 
        WHEN TRUNC(SYSDATE) = TRUNC(e.EMP_HIREDATE) THEN 15
        ELSE FLOOR(MONTHS_BETWEEN(SYSDATE, e.EMP_HIREDATE) / 12) + 15
    END,
    '관리자',  -- 등록자 ID
    SYSDATE,
    '관리자',  -- 수정자 ID
    SYSDATE
FROM EMP e;




SELECT *
	FROM ATT a 
	WHERE EMP_NO = 'AA001';


SELECT COUNT(ATT_ARRIVE_TIME) 
	FROM ATT a 
	WHERE ATT_ARRIVE_TIME > ;


SELECT COUNT(ATT_ARRIVE_TIME)
FROM ATT a
WHERE ATT_ARRIVE_TIME > TRUNC(SYSDATE) + INTERVAL '9' HOUR
AND EMP_NO = 'AA001';


SELECT e.EMP_IMG, e.EMP_NO, e.EMP_NAME, e.EMP_DEPT, e.EMP_POS, 
		e.EMP_GENDER, e.EMP_BIRTH, e.EMP_PHONE, e.EMP_EMAIL, 
		e.EMP_POSTCODE, e.EMP_ADDRESS1, e.EMP_ADDRESS2, 
		e.EMP_ADDRESS3, e.EMP_HIREDATE,
		(SELECT COUNT(a.ATT_ARRIVE_TIME)
		FROM ATT a
		WHERE a.ATT_ARRIVE_TIME > TRUNC(SYSDATE) + INTERVAL '9' HOUR
		AND a.EMP_NO = e.EMP_NO
		) AS late_count,
		(SELECT COUNT(a.ATT_ARRIVE_TIME)
		FROM ATT a
		WHERE a.ATT_ARRIVE_TIME <= TRUNC(SYSDATE) + INTERVAL '9' HOUR
		AND a.EMP_NO = e.EMP_NO) AS right_count ,
		(SELECT COUNT(a.ATT_ARRIVE_TIME)
		FROM ATT a
		WHERE a.ATT_ARRIVE_TIME IS NULL
		AND a.ATT_LEFT_TIME IS NULL
		AND a.EMP_NO = e.EMP_NO) AS empty_count
FROM EMP e
WHERE e.EMP_NO = 'AA001';


SELECT COUNT a.ATT_ARRIVE_TIME > TRUNC(SYSDATE) + INTERVAL '9' HOUR
		) AS late_count,
		COUNT a.ATT_ARRIVE_TIME <= TRUNC(SYSDATE) + INTERVAL '9' HOUR
		 AS right_count ,
		(SELECT COUNT(a.ATT_ARRIVE_TIME)
		FROM ATT a
		WHERE a.ATT_ARRIVE_TIME IS NULL
		AND a.ATT_LEFT_TIME IS NULL
		AND a.EMP_NO = e.EMP_NO) AS empty_count
FROM EMP e
WHERE e.EMP_NO = 'AA001';

    SELECT 
        COUNT(CASE 
                WHEN ATT_ARRIVE_TIME > TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 09:00:00', 'YYYY-MM-DD HH24:MI:SS') THEN 1 
                ELSE NULL 
              END) AS late_count,
        COUNT(CASE 
                WHEN ATT_ARRIVE_TIME <= TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 09:00:00', 'YYYY-MM-DD HH24:MI:SS') THEN 1 
                ELSE NULL 
              END) AS right_count,
            COUNT(CASE
            WHEN ATT_LEFT_TIME IS NOT NULL 
            AND ATT_ARRIVE_TIME IS NOT NULL
            AND ATT_LEFT_TIME < TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 18:00:00', 'YYYY-MM-DD HH24:MI:SS')
            THEN 1
            ELSE NULL
          END) AS early_count,
        SUM(CASE
            WHEN ATT_ARRIVE_TIME IS NULL
            AND ATT_LEFT_TIME IS NULL
            THEN 1
            ELSE 0
        END) AS empty_count
    FROM ATT a
    WHERE EMP_NO = 'AA001'
   	AND TO_CHAR(ATT_ARRIVE_TIME, 'MM') = TO_CHAR(SYSDATE, 'MM');
   
       SELECT 
        COUNT(CASE 
                WHEN ATT_ARRIVE_TIME > TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 09:00:00', 'YYYY-MM-DD HH24:MI:SS') THEN 1 
                ELSE NULL 
              END) AS late_count,
        COUNT(CASE 
                WHEN ATT_ARRIVE_TIME <= TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 09:00:00', 'YYYY-MM-DD HH24:MI:SS') THEN 1 
                ELSE NULL 
              END) AS right_count,
            COUNT(CASE
            WHEN ATT_LEFT_TIME IS NOT NULL 
            AND ATT_ARRIVE_TIME IS NOT NULL
            AND ATT_LEFT_TIME < TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 18:00:00', 'YYYY-MM-DD HH24:MI:SS')
            THEN 1
            ELSE NULL
          END) AS early_count,
        SUM(CASE
            WHEN ATT_ARRIVE_TIME IS NULL
            AND ATT_LEFT_TIME IS NULL
            THEN 1
            ELSE 0
        END) AS empty_count
    FROM ATT a
    WHERE EMP_NO = 'AA001';


   
SELECT *
	FROM ATT a 
	WHERE EMP_NO = 'AA001';
	

-- 년도, 남은 연차 갯수
SELECT EMP_NO, VA_YEAR, 
		(VA_CHECK_NUM - 
			(SELECT COUNT(*)
			FROM VA v 
			WHERE v.EMP_NO = 'AA001'
			AND v.VA_USE_NUM = 1)
			- ((SELECT COUNT(*)
			FROM VA V
			WHERE v.EMP_NO = 'AA001'
			AND v.VA_USE_NUM = 0.5) / 2)
		) AS VA_CHECK
FROM VA_CHECK vc
WHERE vc.EMP_NO = 'AA001'
AND TO_CHAR(SYSDATE, 'YYYY') = TO_CHAR(VA_YEAR, 'YYYY');
	

-- 연차 사용 날짜
SELECT EMP_NO, TO_CHAR(VA_USE_DATE, 'YYYY-MM-DD')
	FROM VA v 
	WHERE EMP_NO = 'AA001'
	AND VA_USE_NUM = 1;

-- 반차 사용 날짜
SELECT EMP_NO, TO_CHAR(VA_USE_DATE, 'YYYY-MM-DD')
	FROM VA v 
	WHERE EMP_NO = 'AA001'
	AND VA_USE_NUM = 0.5;

SELECT *
	FROM VA v ;

-- 올해 연차 사용 횟수
SELECT COUNT(*)
	FROM VA v 
	WHERE VA_USE_NUM = 1
	AND TO_CHAR(VA_USE_DATE, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')
	AND v.EMP_NO = 'AA001';

--올해 반차 사용 횟수
SELECT COUNT(*)
	FROM VA v 
	WHERE VA_USE_NUM = 0.5
	AND TO_CHAR(VA_USE_DATE, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')
	AND v.EMP_NO = 'AA001';


SELECT *
	FROM VA_CHECK vc 
	WHERE EMP_NO = 'AA001';


INSERT INTO GEO.VA
(EMP_NO, APD_NO, VA_USE_NUM, VA_USE_DATE, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
VALUES (
    'AA001', 
    '123', 
    0.5, 
    TO_DATE('2023-09-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
    'EE001', 
    TO_DATE('2023-09-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
    'EE001', 
    TO_DATE('2023-09-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS')
);







