SELECT *
	FROM EMP e ;
	

UPDATE GEO.EMP
SET EMP_STATUS='N', 
EMP_RETIREDATE = SYSDATE
WHERE EMP_NO='SY345';

 SELECT EMP_NO ,
		 		EMP.EMP_NAME AS EMP_NAME,
			    POS.CODE_NAME AS EMP_POS,
			    DEPT.CODE_NAME AS EMP_DEPT
			FROM EMP;
		
SELECT COUNT(*)
	FROM VIEW_COUNT
	WHERE BO_NO =#{bo_no} AND EMP_NO = #{emp_no};