
-- 즐겨찾기 조회 - 즐겨찾기 테이블
SELECT APF_ID, EMP_NO, APD_FORM, REG_ID,TO_CHAR(REG_DATE ,'YYYYMMDD') AS REG_DATE, MOD_ID, TO_CHAR(MOD_DATE ,'YYYYMMDD') AS REG_DATE
 FROM AP_FAV
 WHERE EMP_NO = 'EMP'; 

--결재양식 추가 - 공통 테이블
INSERT INTO GEO.COM
(COMMON_CODE, CODE_NAME, DIVISION, REG_ID, REG_DATE, MOD_ID, MOD_DATE)
VALUES('111', '연차 신청서', '결재양식', 'TEST', SYSDATE, 'TEST', SYSDATE);




--결재양식명 조회 - 공통테이블 / 즐찾 테이블 조인
SELECT CODE_NAME 
 FROM COM c 
 INNER JOIN AP_FAV af 
  	ON af.APD_FORM = c.COMMON_CODE ;
  

-- 즐겨찾기 디비 인서트
INSERT INTO GEO.AP_FAV
(APF_ID, EMP_NO, APD_FORM, REG_ID, REG_DATE, MOD_ID, MOD_DATE, APF_NAME)
VALUES('1', 'EMP',111, 'E', SYSDATE, 'D', SYSDATE, '사유서');